### PR TITLE
docs: Add contributing guide to the docs

### LINKED ISSUE #1307: Add local development guide to docs
Currently, the flow for local development in the beta branch.

1. `git clone git@github.com:infinitered/reactotron.git` - Clone repo
2. `yarn` - Install deps
3. `npx ignite-cli new PizzaApp --yes` - Ignite an app in another repository
4. `npx zx scripts/install-workspace-packages-in-target.mjs $PIZZA_APP_PATH/node_modules` - Install local reactotron modules in target app
5. `yarn start` - Start Reactotron app

Optional scripts:
- `npx nx watch --all -- "npx zx scripts/install-workspace-packages-in-target.mjs $PIZZA_APP_PATH/node_modules"` - watch local Reactotron workspace packages and rebuild in test PizzaApp node_modules on change
- ` nx watch --all -- npx nx run \$NX_PROJECT_NAME:build` - Rebuild local packages

### PR DESCRIPTION
**Pull request by markrickert**
Closes #1307

This adds a step-by-step guide for getting up and running with contributing to reactotron based on my experiences this week.

This PR does not need CI validation or a release when merged.

### CODE REVIEW

**Comment by markrickert** [comment]
@joshuayoes What is the procedure for merging this PR without making a new release... is there a `skip-release` command (or something similar) we can use?

**Comment by joshuayoes** [comment]
@markrickert currently, the nx plugin does a diff of the workspace changes between the last commit and the current commit.

I merged this branch locally and ran the local test command `yarn release:tags:local`, and it showed no changes.

Screenshot 2023-09-29 at 1 19 44 PM

**Review by joshuayoes — APPROVED** [review]
Thanks for this Mark!

**Comment by joshuayoes** [comment]
Also, we have a skip release prefix for `docs` and `release`: https://github.com/infinitered/reactotron/blob/beta/nx.json#L24

**Pull request merged**
