### PR TITLE
Documentation for the release process

### PR DESCRIPTION
**Pull request by skellock**
Hey Rich, I added some notes on how to release Reactotron.

There's lots of opportunity to streamline this process.  This will become very easy to do once we eject Electron.  Reactotron 3.0 will be so much more straight forward.  I'd highly recommend this gets automated.  =)

This week, I'll get you hooked up with the permissions on `npm`.  We can sync up on slack.

/cc @jamonholmgren

### CODE REVIEW

**Comment by rmevans9** [comment]
👍

**Comment by jamonholmgren** [comment]
Looks great, thanks @skellock !

**Pull request merged**
