### PR TITLE
Fix warning when source effect has no effect

### PR DESCRIPTION
**Pull request by megazoll**

### CODE REVIEW

**Comment by skellock** [comment]
Hey, thanks!  This looks fine.  Can you give me a little bit of context around this?  I think this is a bug fix.

**Comment by megazoll** [comment]
Hi!

I'm not yet debug this case, just seen that`sourceEffectInfo` looks like:
```json
{
  "effectId": 56,
  "parentEffectId": 55,
  "label": "",
  "status": "RESOLVED",
  "name": "UNKNOWN",
  "description": "UNKNOWN",
  "startedAt": 89.93727111816406,
  "duration": 0.018214821815490723
}
```
and made quick fix.

**Comment by skellock** [comment]
Interesting.  What was `parentEffectId`?  I wonder why it wasn't in the lookup table?

**Comment by megazoll** [comment]
My saga:
```js
export default function* language() {
    yield takeEvery(SET_LANGUAGE, ({ payload }) => {
        Translator.setLanguage(payload);
    });

    const { language, version } = yield select(pick(['language', 'version']));
    yield put(setLanguage(language));
    Translator.setLocaleVersion(version);
}
```

Effects hierarchy:
```json
{
  "effectId": 62,
  "parentEffectId": 61,
  "label": "",
  "status": "RESOLVED",
  "name": "UNKNOWN",
  "description": "UNKNOWN",
  "startedAt": 133.41261494159698,
  "duration": 0.026845097541809082
}
```

```json
{
  "effectId": 61,
  "parentEffectId": 57,
  "effect": {
    "@@redux-saga/IO": true,
    "FORK": {
      "context": null,
      "fn": "fn()",
      "args": [
        {
          "type": "SET_LANGUAGE",
          "payload": "ru",
          "attrs": null
        }
      ]
    }
  },
  "label": "",
  "status": "RESOLVED",
  "name": "FORK",
  "description": "",
  "startedAt": 132.07462203502655,
  "duration": 6.745812892913818
}
```

```json
{
  "effectId": 57,
  "parentEffectId": 56,
  "effect": {
    "@@redux-saga/IO": true,
    "FORK": {
      "context": null,
      "fn": " takeEvery() ",
      "args": [
        "SET_LANGUAGE",
        "fn()"
      ]
    }
  },
  "label": "",
  "status": "PENDING",
  "name": "FORK",
  "description": "takeEvery",
  "result": {
    "@@redux-saga/TASK": true,
    "id": 57,
    "name": "takeEvery",
    "cont": "fn()",
    "joiners": [],
    "cancel": " cancel() ",
    "isRunning": " isRunning() ",
    "isCancelled": " isCancelled() ",
    "isAborted": " isAborted() ",
    "result": " result() ",
    "error": " error() ",
    "setContext": " setContext() ",
    "done": {
      "_40": 1,
      "_65": 0,
      "_55": null,
      "_72": {
        "onFulfilled": " onTaskResult() ",
        "onRejected": "fn()",
        "promise": {
          "_40": 0,
          "_65": 0,
          "_55": null,
          "_72": null
        }
      }
    }
  },
  "startedAt": 129.70661401748657,
  "duration": 0.11303699016571045
}
```

**Comment by skellock** [comment]
Thanks.  I want to take a closer look at this. I’ll give this is a test run.

When you say “fix warning”, which warning are you referring to?  A linting warning in standard?

**Comment by skellock** [comment]
Oh . Yikes that’s awful. Haha. I see what you’re fixing now.  Thanks.

**Comment by megazoll** [comment]
Seems like that error triggered only when second parameter in `takeEvery` not generator

**Comment by skellock** [comment]
So putting this in has the effect of suppressing all sagas from being sent in the `demo-react-native`.

I even brought `redux-saga` up to 16.x to see if it was something else.

How do you hand over your root saga to the saga middleware on startup?

**Comment by megazoll** [comment]
Oh, sorry, too quick fix. It's much better to do not collect extra data instead of skipping whole effect.

Root saga run in a standard way (there are only some glue for redux-persist)

```js
export default function* rootSaga() {
    yield all([
        ...
        language(),
    ]);
}

export function configureStore(initialState) {
    const store = creatorStore(
        reducer,
        initialState,
        applyMiddleware(...middlewares)
    );

    let persistor = persistStore(store);

    const handlePersistorState = () => {
        let { bootstrapped } = persistor.getState();
        if (bootstrapped) {
            sagaMiddleware.run(rootSaga);
            unsubscribe && unsubscribe();
        }
    };
    let unsubscribe = persistor.subscribe(handlePersistorState);
    handlePersistorState();
    // persistor.purge();

    return { persistor, store };
}
```

**Comment by easybird** [comment]
Nice! Wanted to PR the same fix here. Can this be merged please?

**Comment by kevinmeyvaert** [comment]
Guys, this should've been merged by now. Thanks in advance!

**Comment by thibmaek** [comment]
Great work, would be great if this could make it into the build :)

**Comment by bitcrumb** [comment]
2017 called, can this be merged? 😎
Thanks for the effort!

**Comment by skellock** [comment]
It would have been merged had I been able to reproduce the problem.  =)  I'm not saying it not a thing or that isn't the fix. I just can't make the warning appear.  This makes me sad in the pants.

Can one of you 4 incredibly sync'ed up individuals (@kevinmeyvaert @thibmaek @eliaslecomte @bitcrumb ) do a repro?

Let's get this bad boy merged!

**Comment by easybird** [comment]
Thanks for your quick reply @skellock .
First of all, we love this module!

I will try clean up your sad pants.

Like @megazoll, we also have this warning screen. 
We could pinpoint that in our case, this was due to the fact that we 'forked' something that was not a generator, but a promise.
Due to this, the Reactotron logging for cancelling the upper saga failed. As sourceEffectInfo.effect is undefined. Therefore we received the warning message.

When adding an undefined check like this PR does, you still receive Reactotron logging about the effect, cfr below. Notice the UNKNOWN effect at the end with parentId FORK clearQueue (which isn't a generator function).

Without adding the undefined check, nothing gets logged in Reactotron.

image

I suggest just to merge this PR, as [the saga documentation](https://redux-saga.js.org/docs/api/#forkfn-args) specifies: 

> fork, like call, can be used to invoke both normal and Generator functions

I want to seize the opportunity to 👋 at all those sync'ed up individuals over there!

✌️

**Comment by skellock** [comment]
Thanks for the PR and thanks for the follow up!  Go team internet!

**Comment by thibmaek** [comment]
Thanks a bunch from our whole team Steve!

**Pull request merged**
