### PR TITLE
Socket.io -> WebSocket for simplicity.

### PR DESCRIPTION
**Pull request by rmevans9**
This is @skellock's work rebased up to the latest master.

### CODE REVIEW

**Comment by skellock** [comment]
I think something might have gone awry with this @rmevans9.

I tried in a new branch to rebase and it gave me these conflicts as well, but after resolving them, it worked fine.

I pushed these up to a new branch `v2`.  I *think* these are the same changes you just made.

If you can, try: `git checkout v2` and `yarn` and `yarn run welcome`.

(`reactotron-app` is still a bit squirrely with installing via `yarn` because of the electron post-install hooks... blargh.  Sometimes just running `yarn` by itself in `packages/reactotron-app` fixes that.  Follow that by a `cd ../..` and `yarn run bootstrap` to re-lerna-ify.)

So if that works for you, I'd say, let's make that the branch for `v2` things and close this PR.

Thanks a million man.

**Comment by rmevans9** [comment]
Sorry, for the delay in testing your suggestion. Giving it a go right now

**Comment by rmevans9** [comment]
I seem to be having issues building the v2 branch. When it goes to run `yarn run build` it errors out with `Cannot read property 'split' of undefined`. Stack trace indicates that it is in the minimatch module when that occurs. Trying to see if I can figure out what the heck is going on...

**Comment by rmevans9** [comment]
Closing in favor of the v2 branch

**Pull request closed without merging**
