### PR TITLE
[Needs Help] - Rename state

### PR DESCRIPTION
**Pull request by GantMan**
Live from Amsterdam, almost functioning PR needs lil help
snapshots

### CODE REVIEW

**Comment by GantMan** [comment]
Just need to know how to mobx that data back to where it needs to go.  Maybe a quick screen sesh would do it.  I kinda see what we do, but not too sure.

**Comment by skellock** [comment]
Sweet.  Now [something like this](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Stores/UiStore.js#L219) but for renaming?

**Comment by GantMan** [comment]
I'm a little lost on the `this.server.commands['state.backup.response'].remove(state)` since I can't seem to figure out what commands are.  I could pass the backup around and then modify it in the final event, but that seems dirty.  I'm not sure what the best practice should be.

**Comment by skellock** [comment]
The commands come from reactotron-core-server. Its a map of command names to the latest 100 messages for each.

Not sure what you're getting at about best practices. Is there better ways to build this? Absolutely.

This works pretty good. Has for a year. I'm all ears if you're thinking of refactoring.

**Comment by skellock** [comment]
renamesnapshot

**Comment by GantMan** [comment]
lookin good

**Pull request merged**
