### PR TITLE
Add app name more places

### PR DESCRIPTION
**Pull request by lindboe**
Add the app name on Home and bottom connection bar. Always show the app name passed in by the app establishing the Reactotron connection. If it's not set, let the user know it's unknown so they know it's possible to add. Fixes https://github.com/infinitered/reactotron/issues/1351.

Worked on by @carlinisaacson @darinwilson and @lindboe !

**Home screen with connections**
Screenshot 2023-12-15 at 10 19 37 AM

**Bottom bar, collapsed**
Screenshot 2023-12-15 at 10 20 05 AM

**Bottom bar, expanded**
Screenshot 2023-12-15 at 10 20 23 AM

### CODE REVIEW

**Review by jamonholmgren — APPROVED** [review]
Looks great!

**Review by joshuayoes — APPROVED** [review]
Great job with this!

**Comment by darinwilson** [comment]
It's a good thing I was part of this team. Those two would have been lost without me. Lost, I tell you.

**Comment by jamonholmgren** [comment]
Proper PHP CEO credit where it is due, @darinwilson!

**Pull request merged**
