### PR TITLE
Tabs - Another approach

### PR DESCRIPTION
**Pull request by rmevans9**
This is to show another approach I thought of while working on moving the tabs around.

### CODE REVIEW

**Comment by rmevans9** [comment]
👍 I will get the RN tab up to using this method tonight. I am not sure if we are ready to add the new "main" tab with the stats yet so it might make sense to get the RN tab updated and then merge this and loop back on the new tab for stats and other information on another PR.

**Comment by skellock** [comment]
Good call.  Make we could land #653 with #606 so they can live together on our "main"/"home" screen?

**Comment by rmevans9** [comment]
Sounds good to me. I will get this one ready to land then update 653 and 606 to live on a new tab. I might merge them into the same branch so I can just knock both out quickly and be ready to land em.

**Comment by rmevans9** [comment]
This switches all of the headers minus Timeline over. Still need to change up the collapse arrow and move that to the menu

**Comment by rmevans9** [comment]
@skellock That should wrap this PR up.

**Comment by skellock** [comment]
👍

**Pull request merged**
