### PR TITLE
Add preview for object, null and undefined

### PR DESCRIPTION
**Pull request by megazoll**

### CODE REVIEW

**Comment by rmevans9** [comment]
I think I understand what this code is trying to solve but just to be sure can you add a screenshot to this PR showing the before/after of this change when previewing an object?

**Comment by megazoll** [comment]
Added clipping strings and screenshots

```js
    console.tron.log(undefined);
    console.tron.log(null);
    console.tron.log({});
    console.tron.log({
        a: undefined
    })
    console.tron.log({
        a: undefined,
        d: {
            c: 1
        }
    })
    console.tron.log({
        a:1,
        b:2,
        c:3,
        d:4,
        e:5,
        f:6,
        g:7,
        h:8
    });
    console.tron.log({
        text: 'qweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqwe',
        text2: ''
    });
```

Master:


PR:

**Comment by skellock** [comment]
Perfect!

**Comment by rmevans9** [comment]
This is awesome. Thanks @megazoll!

**Comment by henrikra** [comment]
@skellock Can you make new release since this is nice feature!

**Comment by skellock** [comment]
Ok, 1.14 is out.  `brew` is still approving/seed.  Usually takes a few hours.  You can grab the binary from the release if you need it now.

**Comment by henrikra** [comment]
@megazoll Can you add preview for booleans too?
Now if I do `console.tron.log(false);` the preview is empty :/

**Pull request merged**
