### PR TITLE
Copy subscription path

### LINKED ISSUE #575: Copy subscription path to clipboard
Can't copy previously added subscriptions paths.

Reactotron 1.14.0

### PR DESCRIPTION
**Pull request by JulienMalige**
Fix  #575

You can now select and copy a subscription path. 

To prevent a UX conflict with the "unsubscribe" action, I propose to add an "Unsubscribe" button.

Not sure about which icons combination to use (note that I changed "Unsubscribe All" icon of the header):

capture d ecran 2018-10-13 a 18 46 42
capture d ecran 2018-10-13 a 18 47 16
capture d ecran 2018-10-13 a 18 47 38

### CODE REVIEW

**Comment by rmevans9** [comment]
The Backups tab uses the trash can in your last image. I believe that is the one in use in the PR here. Can you confirm that? If so this looks good to me.

**Comment by rmevans9** [comment]
Thanks for updating that. LGTM!

**Comment by JulienMalige** [comment]
I did not see that Backups tab was using a similar button. I added a commit to harmonize this 2 tabs (code + ui).

capture d ecran 2018-10-14 a 11 31 31
capture d ecran 2018-10-14 a 11 31 25

**Comment by JulienMalige** [comment]
Last little change 😄, watchValue is also selectable (cursor stays pointer because it can be text or tree).

**Comment by rmevans9** [comment]
Sorry for the delay in getting to this. I had to do a bunch of work around the CI/CD process. I have updated the branch and ensured there were no conflicts. Merging now (finally!). I am very sorry for the delay @JulienMalige

**Pull request merged**
