### PR TITLE
Persist timeline filter settings

### PR DESCRIPTION
**Pull request by megazoll**

### CODE REVIEW

**Comment by henrikra** [comment]
I would love to have this feature!! Can you also make feature where Reactotron clears time line on reload? :)

**Comment by megazoll** [comment]
@henrikra https://github.com/infinitered/reactotron/blob/master/docs/tips.md#clearing-reactotron

**Comment by henrikra** [comment]
Good tip! I still think that this should be configured in Reactotron UI with checkbox for example. It does not make sense for me to change my code when I want to change settings of a running app :P

**Comment by skellock** [comment]
@henrikra I agree with that.  Feel free to open another issue to track that!

**Comment by henrikra** [comment]
"Woah, I had no idea that localStorage worked in electron." Well Electron is just a browser :D

**Comment by skellock** [comment]
Haha... i have a long history of not putting 2 and 2 together.

**Pull request merged**
