### PR TITLE
Export timeline

### PR DESCRIPTION
**Pull request by robinfehr**
let's discuss the details based on this PR. feel free to pm me directly on gitter.

TODO: 
- shortcut for accessing file export dialog.

### CODE REVIEW

**Comment by mlaco** [comment]
Hey @robinfehr thanks so much for your PR! We will review it as our bandwidth allows.

**Comment by thibmaek** [comment]
This would be a huge help for our team as well!

**Comment by rmevans9** [comment]
@robinfehr thank you for this PR. I took a look at the code and everything looks good there. I am going to pull this locally and give it a try before merging just to make sure I understand how it is all working together. I should be able to do that tomorrow. Sorry for the long delay in getting back on this!

**Comment by rmevans9** [comment]
@robinfehr I have merged in dev as I did a bunch of reorganizing of the repo. I tested it out and it appears to work well so going to go ahead and merge it on in. Thank you!

**Comment by robinfehr** [comment]
@rmevans9 thanks for the effort.

**Pull request merged**
