### PR TITLE
Add Expo quick start example

### LINKED ISSUE #1107: Can't get Reactotron to Connect to Expo App
Title says it all.
When I run basic test app on iOS simulator, I get 'Reactotron Configured' in the console log, but Reactotron app does not connect on Mac.
Have tried *a lot* of configuration variants etc based on prior posts.
Currently, trying to do something very basic... just get a bare expo react native app to run on a simulator and connect to Reactotron.
I've downloaded the latest version, and followed the react native install instructions (many times).

Currently using the simplest config options:
in ReactotronConfig.js:
import Reactotron from 'reactotron-react-native'
Reactotron
    .configure({
        name: "React Native Demo",
    }) // controls connection & communication settings
   // .useReactNative() // add all built-in react native plugins
    .connect() // let's connect!

in App.js:
if(__DEV__) {
  import('./ReactotronConfig').then(() => console.log('Reactotron Configured'))
}

from package.json:
    "reactotron-react-native": "^3.6.4"
    "expo": "^33.0.0",
    "react": "16.8.3",

Thanks for your help.

### PR DESCRIPTION
**Pull request by karlhorky**
First of all, thanks for this project! 🙌 Really great for debugging.

Just a quick PR to add a quick start example for those using Expo, so that there are fewer issues from users as described in #417

Closes #1107

cc @mazenchami  @jamonholmgren

### CODE REVIEW

**Comment by karlhorky** [comment]
Seems like the CI failure is unrelated:

```
Build-agent version 1.0.135211-b712450b (2022-08-08T15:42:46+0000)
Creating a dedicated VM with xcode:11.1.0 image
failed to create host: Image xcode:11.1.0 is not supported

failed to create host: Image xcode:11.1.0 is not supported
```

**Comment by frankcalise** [comment]
@karlhorky Would you mind updating the PR to merge it into the `beta` branch over `master`? The CI should pass there and a bunch more updates to come out in the next version.

**Comment by karlhorky** [comment]
@frankcalise done! Not sure if I have access to re-run the CI job on CircleCI though.

**Comment by frankcalise** [comment]
@karlhorky Thanks I'll get @jamonholmgren to kick it off (and perhaps give me access too)

**Comment by frankcalise** [comment]
@karlhorky Nice work! Just tested it with a regular old Expo initialized app and worked no problem.

Do you mind just updating the following in the 4 snippet examples: 

```
// AsyncStorage would either come from `react-native` or `@react-native-community/async-storage` depending on where you get it from
```

Since AsyncStorage is deprecated in react-native core let's update the comment to something like:

```
// AsyncStorage would either come from `@react-native-async-storage/async-storage` or `@react-native-community/async-storage` 
```

**Comment by karlhorky** [comment]
Great, thanks :) Updated the AsyncStorage comments in d763bcbb6e98f1542b69f0a918a7906219db82a9

**Comment by karlhorky** [comment]
Thanks for the merge!

**Comment by frankcalise** [comment]
@karlhorky Thanks for the contribution! Hopefully we release this version soon.

Right @jamonholmgren 😉

**Pull request merged**
