### PR TITLE
Update react-native to 0.61.3

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates `react-native` in `demo-react-native` and `ReactotronTester` to `0.61.3` including all project support files.

For more information about React Native 0.60 check the official announcement: https://facebook.github.io/react-native/blog/2019/07/03/version-60

Successfully verified and tested on:
- Android Device (Xiaomi Mi A2)
- Android Emulator (Pixel 3a)
- iOS Device (iPhone 8)
- iOS Simulator (iPhone X)

### CODE REVIEW

**Comment by friederbluemle** [comment]
@skellock @rmevans9 - Please take a look at this PR if you have a few minutes. 🙏

**Comment by friederbluemle** [comment]
Updated to 0.61.2

**Comment by friederbluemle** [comment]
Updated to `0.61.3`

**Comment by rmevans9** [comment]
Hey @friederbluemle sorry for the delay! Taking a look a this right now

**Comment by rmevans9** [comment]
LGTM!

**Pull request merged**
