### PR TITLE
chore(tools): Update a lot of development workflow packages and move to modern  & consistent `rollup` configuration

### PR DESCRIPTION
**Pull request by markrickert**
This PR updates a lot of behind-the-scenes tools like `nx` and `rollup`.

I completely replaced the old 1.x and 2.x rollup configuration and old deprecated plugins with their latest and greatest versions.

rollup config files were all renamed to `rollup.config.cjs` and now use the `@rollup/plugin-typescript` instead of the old babel integration.

I also updated `@jscutlery/semver` and related dependencies to the latest version as well. There's a small risk that this might break CI, but 🤞

### CODE REVIEW

**Comment by markrickert** [comment]
Of note, there are some `electron` minor package updates in this PR as well.

**Review by joshuayoes — APPROVED** [review]
I did a spot of the `/dist` output and installed all the packages into an Ignite app as well, it all looks good!

**Comment by markrickert** [comment]
Looks like nothing broke!

**Comment by markrickert** [comment]
I was wrong. 😭

**Pull request merged**
